In [1]:
import numpy as np
a=np.array([[1,2,3],[1,2,3],[1,2,3]])
c,d=np.linalg.eig(a)
print(c)
print()
print(d)

[ 6.00000000e+00  4.03541664e-17 -2.96106259e-16]

[[ 0.57735027 -0.06824394  0.91960957]
 [ 0.57735027 -0.81946204 -0.39007323]
 [ 0.57735027  0.569056   -0.0464877 ]]


In [2]:
import numpy as geek
 
#Working on 1D
arr1 = geek.arange(8).reshape(2, 4)
print("2D arr1 : \n", arr1)
print("Shape : ", arr1.shape)
 
arr2 = geek.arange(8, 16).reshape(2, 4)
print("\n2D arr2 : \n", arr2)
print("Shape : ", arr2.shape)
 
arr3 = geek.append(arr1, arr2)
print("\nAppended arr3 by flattened : ", arr3)
 
# appending the arrays with axis = 0 row wise
arr3 = geek.append(arr1, arr2, axis = 0)
print("\nAppended arr3 with axis 0 : \n", arr3)
 
# appending the arrays with axis = 1  column wise
arr3 = geek.append(arr1, arr2, axis = 1)
print("\nAppended arr3 with axis 1 : \n", arr3)

2D arr1 : 
 [[0 1 2 3]
 [4 5 6 7]]
Shape :  (2, 4)

2D arr2 : 
 [[ 8  9 10 11]
 [12 13 14 15]]
Shape :  (2, 4)

Appended arr3 by flattened :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

Appended arr3 with axis 0 : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Appended arr3 with axis 1 : 
 [[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]]


In [3]:
print(arr1.T)  #transpose
print(arr1)

[[0 4]
 [1 5]
 [2 6]
 [3 7]]
[[0 1 2 3]
 [4 5 6 7]]


In [4]:
arr1.shape

(2, 4)

In [5]:
np.ndim(arr1)

2

# Creation of DataFrame(diff types)


In [6]:
#df using dict of lists

import pandas as pd
data={'name':['siva','mani','ramu'],
        'roll':['cs174','cs234','cs345'],
     'age':[20,19,21]}
df=pd.DataFrame(data)
df

name   roll  age
0  siva  cs174   20
1  mani  cs234   19
2  ramu  cs345   21

In [7]:
#df using dict of numpy arrays

import numpy as np
import pandas as pd 
nparray = np.array(
    [['Emma', 'Oliver', 'Harry', 'Sophia'],
     [29, 25, 33, 24],
     ['HR', 'Finance', 'Marketing', 'IT']])
pdarray={
    "name":nparray[0],
    "Age":nparray[1],
    "Dept":nparray[2]
}
df2=pd.DataFrame(pdarray)
df2

name Age       Dept
0    Emma  29         HR
1  Oliver  25    Finance
2   Harry  33  Marketing
3  Sophia  24         IT

In [8]:
#dict using lists of lists

list_of_lists = [
    ['Emma', 29, 'HR'],
    ['Oliver', 25, 'Finance'],
    ['Harry', 33, 'Marketing'],
    ['Sophia', 24, 'IT']]
df2=pd.DataFrame(list_of_lists,columns=['Name','Age',"Department"])
df2

Name  Age Department
0    Emma   29         HR
1  Oliver   25    Finance
2   Harry   33  Marketing
3  Sophia   24         IT

In [9]:
# df using lists of dicts

list_of_dict=[
    {"name":"emma","age":25,"Dept":"HR"},
    {"name":"Harrat","age":26,"Dept":"finance"},
    {"name":"Sohail","age":29,"Dept":"IT"}
]
df4=pd.DataFrame(list_of_dict)
df4.index.name="Emp"             # with row names
df4

name  age     Dept
Emp                      
0      emma   25       HR
1    Harrat   26  finance
2    Sohail   29       IT

In [10]:
# using dict of Pandas Series

s1=pd.Series(["emma","Harrat","Kohli"])
s2=pd.Series([25,24,23])
s3=pd.Series(['HR',"Fonance","IT"])

da={"Name":s1,"Age":s2,"Dept":s3}

df5=pd.DataFrame(da)
df5

Name  Age     Dept
0    emma   25       HR
1  Harrat   24  Fonance
2   Kohli   23       IT

In [12]:
df2.head(3) #head -first 5 rows

Name  Age Department
0    Emma   29         HR
1  Oliver   25    Finance
2   Harry   33  Marketing

In [14]:
df2.tail(3)   #tail -last 5 rows

Name  Age Department
1  Oliver   25    Finance
2   Harry   33  Marketing
3  Sophia   24         IT

In [15]:
df2.info   #info - about df2

<bound method DataFrame.info of      Name  Age Department
0    Emma   29         HR
1  Oliver   25    Finance
2   Harry   33  Marketing
3  Sophia   24         IT>

In [16]:
df2.shape # shape- tuple(rows,cols)

(4, 3)

In [17]:
df2.describe()   #describe - gives statistical data of df2

Age
count   4.000000
mean   27.750000
std     4.112988
min    24.000000
25%    24.750000
50%    27.000000
75%    30.000000
max    33.000000

In [18]:
df2.ndim   # ndim - checks what is dimension of df2

2

In [19]:
df2.columns   #columns - what are the columns

Index(['Name', 'Age', 'Department'], dtype='object')

In [21]:
df2.size    # size- no. of data items in total df2 ,i.e, shape=(4,3) =12 items(size)

12

In [22]:
df2.dtypes  #daata types of df2

Name          object
Age            int64
Department    object
dtype: object

In [24]:
df2["Age"].dtype   # dtype of particular column

dtype('int64')

In [27]:
df2[df2["Age"]>28]   # filtering the dataframes by condition - df[Age > 28]

Name  Age Department
0   Emma   29         HR
2  Harry   33  Marketing

In [28]:
df2  

Name  Age Department
0    Emma   29         HR
1  Oliver   25    Finance
2   Harry   33  Marketing
3  Sophia   24         IT

In [30]:
df2["Name"]   #accessing single column -1

0      Emma
1    Oliver
2     Harry
3    Sophia
Name: Name, dtype: object

In [31]:
df2.Name  #accessing single column -2

0      Emma
1    Oliver
2     Harry
3    Sophia
Name: Name, dtype: object

In [34]:
df2[["Name","Department"]]   # accesing multiple columns

Name Department
0    Emma         HR
1  Oliver    Finance
2   Harry  Marketing
3  Sophia         IT

In [39]:
df2.loc[1,["Name","Age"]]   #index 1 data is accessed using 'loc[]'  and also only some columns of data

Name    Oliver
Age         25
Name: 1, dtype: object

In [38]:
df2[2:4]   #slicing of df2

Name  Age Department
2   Harry   33  Marketing
3  Sophia   24         IT

In [41]:
df2.index.name = 'id'       # Name of the Rows
df2.columns.name = 'item'     # NAme of columns
df2

item    Name  Age Department
id                          
0       Emma   29         HR
1     Oliver   25    Finance
2      Harry   33  Marketing
3     Sophia   24         IT