# IRIS 

In [10]:
iris=np.genfromtxt('Z:\iris\iris.data',delimiter=',',dtype=str)
iris

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
       ['5.1

In [15]:
s=np.genfromtxt('Z:\iris\iris.data',delimiter=',')
de=np.delete(s,4,axis=1)
de

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [20]:
print("The shape is: ",de.shape)


The shape is:  (150, 4)


In [21]:
print("The size is: ",de.size)

The size is:  600


In [22]:
print("The dimension is: ",de.ndim)

The dimension is:  2


In [25]:
iris1,iris2,iris3= np.split(de,3)
print("iris 1 :\n",iris1)
print("iris 2 :\n",iris2)
print("iris 3 :\n",iris3)

iris 1 :
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]]
iris 2 :
 [[7.  3.2 4.7 1.4]
 [6.4 3.2 

In [26]:
header= np.array(['sepal length','sepal width','petal length','petal width'])
print(header)

['sepal length' 'sepal width' 'petal length' 'petal width']


In [47]:
iris_min, iris_max, iris_avg, iris_std, iris_var = np.array([]), np.array([]), np.array([]) , np.array([]), np.array([])
for i in range(iris.shape[1]-1):
    iris_min = np.append(iris_min, de[:,i].min())
    iris_max = np.append(iris_max, de[:,i].max())
    iris_avg = np.append(iris_avg, de[:,i].mean())
    iris_std = np.append(iris_std, de[:,i].std())
    iris_var = np.append(iris_var, de[:,i].var())

print("Minimum values:")
for i in range(len(header)):
    print('\t',header[i], end=' ')
    print('%.2f'%iris_min[i])
print("Maximum values:")
for i in range(len(header)):
    print('\t',header[i], end=' ')
    print('%.2f'%iris_max[i])
print("Mean values:")
for i in range(len(header)):
    print('\t',header[i], end=' ')
    print('%.2f'%iris_avg[i])
print("Standard Deviation values:")
for i in range(len(header)):
    print('\t',header[i], end=' ')
    print('%.2f'%iris_std[i])
print("Variance values:")
for i in range(len(header)):
    print('\t',header[i], end=' ')
    print('%.2f'%iris_var[i])

Minimum values:
	 sepal length 4.30
	 sepal width 2.00
	 petal length 1.00
	 petal width 0.10
Maximum values:
	 sepal length 7.90
	 sepal width 4.40
	 petal length 6.90
	 petal width 2.50
Mean values:
	 sepal length 5.84
	 sepal width 3.05
	 petal length 3.76
	 petal width 1.20
Standard Deviation values:
	 sepal length 0.83
	 sepal width 0.43
	 petal length 1.76
	 petal width 0.76
Variance values:
	 sepal length 0.68
	 sepal width 0.19
	 petal length 3.09
	 petal width 0.58


In [54]:
iris1_min, iris1_max, iris1_avg, iris1_std = np.array([]), np.array([]), np.array([]) , np.array([])
for i in range(de.shape[1]):
    iris1_min = np.append(iris1_min, iris1[:,i].min())
    iris1_max = np.append(iris1_max, iris1[:,i].max())
    iris1_avg = np.append(iris1_avg, iris1[:,i].mean())
    iris1_std = np.append(iris1_std, iris1[:,i].std())
    
print("Maximum values iris1:")
for i in range(len(header)):
    print('\t',header[i],end=" ")
    print('%.2f'%iris1_max[i])
print("Minimum values iris1:")
for i in range(len(header)):
    print('\t',header[i],end=" ")
    print('%.2f'%iris1_min[i])
    
print("Average values iris1:")
for i in range(len(header)):
    print('\t',header[i],end=" ")
    print('%.2f'%iris1_avg[i])

print("Standard deviation values iris1:")
for i in range(len(header)):
    print('\t',header[i],end=" ")
    print('%.2f'%iris1_std[i])

Maximum values iris1:
	 sepal length 5.80
	 sepal width 4.40
	 petal length 1.90
	 petal width 0.60
Minimum values iris1:
	 sepal length 4.30
	 sepal width 2.30
	 petal length 1.00
	 petal width 0.10
Average values iris1:
	 sepal length 5.01
	 sepal width 3.42
	 petal length 1.46
	 petal width 0.24
Standard deviation values iris1:
	 sepal length 0.35
	 sepal width 0.38
	 petal length 0.17
	 petal width 0.11


In [58]:
iris2_min, iris2_max, iris2_avg, iris2_std = np.array([]), np.array([]), np.array([]) , np.array([])
for i in range(iris.shape[1]-1):
    iris2_min = np.append(iris2_min, iris2[:,i].min())
    iris2_max = np.append(iris2_max, iris2[:,i].max())
    iris2_avg = np.append(iris2_avg, iris2[:,i].mean())
    iris2_std = np.append(iris2_std, iris2[:,i].std())
    
print("Minimum values iris2:")
for i in range(len(header)):
    print('\t',header[i], end=' ')
    print('%.2f'%iris2_min[i])
print("Maximum values iris2:")
for i in range(len(header)):
    print('\t',header[i], end=' ')
    print('%.2f'%iris2_max[i])
print("Mean values iris2:")
for i in range(len(header)):
    print('\t',header[i], end=' ')
    print('%.2f'%iris2_avg[i])
print("Standard Deviation values iris2:")
for i in range(len(header)):
    print('\t',header[i], end=' ')
    print('%.2f'%iris2_std[i])

Minimum values iris2:
	 sepal length 4.90
	 sepal width 2.00
	 petal length 3.00
	 petal width 1.00
Maximum values iris2:
	 sepal length 7.00
	 sepal width 3.40
	 petal length 5.10
	 petal width 1.80
Mean values iris2:
	 sepal length 5.94
	 sepal width 2.77
	 petal length 4.26
	 petal width 1.33
Standard Deviation values iris2:
	 sepal length 0.51
	 sepal width 0.31
	 petal length 0.47
	 petal width 0.20


In [59]:
iris3_min, iris3_max, iris3_avg, iris3_std = np.array([]), np.array([]), np.array([]) , np.array([])
for i in range(iris.shape[1]-1):
    iris3_min = np.append(iris3_min, iris3[:,i].min())
    iris3_max = np.append(iris3_max, iris3[:,i].max())
    iris3_avg = np.append(iris3_avg, iris3[:,i].mean())
    iris3_std = np.append(iris3_std, iris3[:,i].std())
    
print("Minimum values iris3:")
for i in range(len(header)):
    print('\t',header[i], end=' ')
    print('%.2f'%iris3_min[i])
print("Maximum values iris2:")
for i in range(len(header)):
    print('\t',header[i], end=' ')
    print('%.2f'%iris3_max[i])
print("Mean values iris2:")
for i in range(len(header)):
    print('\t',header[i], end=' ')
    print('%.2f'%iris3_avg[i])
print("Standard Deviation values iris2:")
for i in range(len(header)):
    print('\t',header[i], end=' ')
    print('%.2f'%iris3_std[i])

Minimum values iris3:
	 sepal length 4.90
	 sepal width 2.20
	 petal length 4.50
	 petal width 1.40
Maximum values iris2:
	 sepal length 7.90
	 sepal width 3.80
	 petal length 6.90
	 petal width 2.50
Mean values iris2:
	 sepal length 6.59
	 sepal width 2.97
	 petal length 5.55
	 petal width 2.03
Standard Deviation values iris2:
	 sepal length 0.63
	 sepal width 0.32
	 petal length 0.55
	 petal width 0.27


In [68]:
compare=[[] for i in range(len(header))]
for i in range(len(compare)):
    compare[i].append(True if iris1_min[i] > iris_min[i] else False)
    compare[i].append(True if iris2_min[i] > iris_min[i] else False)
    compare[i].append(True if iris3_min[i] > iris_min[i] else False)

# Compare the min values of whole data set and separate species

In [67]:
df=pd.DataFrame(compare ,index=header, columns=["Iris Setosa", "Iris Virginica","Iris Versicolor"])
df

Iris Setosa  Iris Virginica  Iris Versicolor
sepal length        False            True             True
sepal width          True           False             True
petal length        False            True             True
petal width         False            True             True

# Compare Iris setosa's avg sepal length to  that of iris virginica

In [71]:
sps, vals = ['Iris setosa', 'Iris virginica'], [iris1_avg[1], iris2_avg[1]]
spNames, avgs = (sps, vals) if iris1_avg[1] > iris2_avg[1] else (sps[::-1], vals[::-1]) 
print(f"The avg sepal width of {spNames[0]} {avgs[0]:.2f} is greater than {spNames[1]} {avgs[1]:.2f}")

The avg sepal width of Iris setosa 3.42 is greater than Iris virginica 2.77


# Compare Iris setosa's avg petal length to that of Iris virginica


In [73]:
sps, vals = ['Iris setosa', 'Iris virginica'], [iris1_avg[2], iris2_avg[2]]
spNames, avgs = (sps, vals) if iris1_avg[2] > iris2_avg[2] else (sps[::-1], vals[::-1]) 
print(f"The avg petal length of {spNames[0]} {avgs[0]:.2f} is greater than {spNames[1]} {avgs[1]:.2f}")

The avg petal length of Iris virginica 4.26 is greater than Iris setosa 1.46


# Compare Iris setosa's avg petal width to that of Iris virginica

In [74]:
sps, vals = ['Iris setosa', 'Iris virginica'], [iris1_avg[3], iris2_avg[3]]
spNames, avgs = (sps, vals) if iris1_avg[3] > iris2_avg[2] else (sps[::-1], vals[::-1]) 
print(f"The avg petal width of {spNames[0]} {avgs[0]:.2f} is greater than {spNames[1]} {avgs[1]:.2f}")

The avg petal width of Iris virginica 1.33 is greater than Iris setosa 0.24


# Save the array iris_avg in a CSV file named IrisMeanValues.txt

In [78]:
saved=np.savetxt("IrisMeanValues.txt",iris_avg,delimiter=', ',fmt='%.2f')
saved

# Save the arrays iris_max, iris_avg, iris_min in a comma seperated file named IrisStat.txt on the hard disk

In [79]:
iris_stat = np.vstack((iris_max, iris_avg, iris_min))
np.savetxt('IrisStat.txt', iris_stat, delimiter=', ', fmt='%.2f')